// +build !

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/example-inc/minizenko-operator/pkg/apis/minizenko/v1alpha1.Minizenko":       schema_pkg_apis_minizenko_v1alpha1_Minizenko(ref),
		"github.com/example-inc/minizenko-operator/pkg/apis/minizenko/v1alpha1.MinizenkoSpec":   schema_pkg_apis_minizenko_v1alpha1_MinizenkoSpec(ref),
		"github.com/example-inc/minizenko-operator/pkg/apis/minizenko/v1alpha1.MinizenkoStatus": schema_pkg_apis_minizenko_v1alpha1_MinizenkoStatus(ref),
	}
}

func schema_pkg_apis_minizenko_v1alpha1_Minizenko(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Minizenko is the Schema for the minizenkos API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/example-inc/minizenko-operator/pkg/apis/minizenko/v1alpha1.MinizenkoSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/example-inc/minizenko-operator/pkg/apis/minizenko/v1alpha1.MinizenkoStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/example-inc/minizenko-operator/pkg/apis/minizenko/v1alpha1.MinizenkoSpec", "github.com/example-inc/minizenko-operator/pkg/apis/minizenko/v1alpha1.MinizenkoStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_minizenko_v1alpha1_MinizenkoSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "MinizenkoSpec defines the desired state of Minizenko",
				Properties: map[string]spec.Schema{
					"cloudServer": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/example-inc/minizenko-operator/pkg/apis/minizenko/v1alpha1.CloudSpecServer"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/example-inc/minizenko-operator/pkg/apis/minizenko/v1alpha1.CloudSpecServer"},
	}
}

func schema_pkg_apis_minizenko_v1alpha1_MinizenkoStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "MinizenkoStatus defines the observed state of Minizenko",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
